'use strict';
function togglePause(force){if(state!=='playing'&&state!=='paused')return;paused=force??!paused;state=paused?'paused':'playing';$('#pause').classList.toggle('hidden',!paused)}
function quitLobby(){state='menu';paused=false;$('#pause').classList.add('hidden');$('#announcement').classList.add('hidden');$('#menu').classList.remove('hidden');$('#topbar').classList.add('hidden');}
function loop(ts){let dt=Math.min(.033,(ts-last)/1000||0);last=ts;time+=dt;if(state==='playing'&&!paused){music(dt);if(!roundLocked){updatePlayers(dt);updateBombs(dt);updateFlames(dt)}updateEffects(dt);checkRound(dt)}else updateEffects(dt*.3);draw();pressed.clear();requestAnimationFrame(loop)}

window.addEventListener('keydown',e=>{const used=CONTROLS.flatMap(c=>['up','left','down','right','bomb','skill'].flatMap(k=>c[k])).includes(e.code)||e.code==='Escape';if(used)e.preventDefault();if(!keys.has(e.code))pressed.add(e.code);keys.add(e.code);if(e.code==='Escape'){if(state==='playing'||state==='paused')togglePause()}});
window.addEventListener('keyup',e=>keys.delete(e.code));window.addEventListener('blur',()=>{keys.clear();if(state==='playing')togglePause(true)});
$('#startBtn').onclick=startGame;$('#helpBtn').onclick=()=>showHelp(true);$('#closeHelp').onclick=()=>showHelp(false);$('#help').onclick=e=>{if(e.target===$('#help'))showHelp(false)};$('#pauseBtn').onclick=()=>togglePause(true);$('#resumeBtn').onclick=()=>togglePause(false);$('#restartBtn').onclick=()=>{players.forEach(p=>p.wins=0);round=1;newRound()};$('#quitBtn').onclick=quitLobby;$('#lobbyBtn').onclick=quitLobby;$('#soundBtn').onclick=()=>{audioOn=!audioOn;$('#soundBtn').textContent=`音效：${audioOn?'開':'關'}`;saveSettings();if(audioOn)unlockAudio()};$('#wins').onchange=()=>{targetWins=+$('#wins').value;saveSettings()};$('#density').onchange=()=>{density=+$('#density').value;saveSettings()};$('#loot').onchange=()=>{loot=+$('#loot').value;saveSettings()};
// 供自動測試與瀏覽器開發者工具檢查；只暴露可見戰局與 AI 決策摘要。
window.BomberAI=Object.freeze({
 levels:Object.fromEntries(Object.entries(AI_LEVELS).map(([id,c])=>[id,{...c}])),
 snapshot:()=>players.filter(p=>p.type==='ai').map(p=>({id:p.id,name:p.name,difficulty:AI_LEVELS[p.aiLevel]?.label,mode:p.aiMode,dangerETA:Number.isFinite(p.aiDangerETA)?p.aiDangerETA:null,goal:p.aiGoal,waypoint:p.aiWaypoint,route:p.aiRoute.map(n=>({...n})),routeIndex:p.aiRouteIndex,routeLocked:p.aiRouteLock,lastRecovery:p.aiLastRecovery,stats:{...p.aiStats},alive:p.alive,ghost:p.ghost,ghostTrack:p.ghostTrack,ghostBomb:p.ghostBomb&&!p.ghostBomb.dead?{airborne:!!p.ghostBomb.airborne,target:p.ghostBomb.airborne?[p.ghostBomb.airborne.toX,p.ghostBomb.airborne.toY]:[Math.floor(p.ghostBomb.x),Math.floor(p.ghostBomb.y)],fuse:p.ghostBomb.fuse}:null,hp:p.hp,lastHit:p.lastHit||null,position:[p.x,p.y],tile:[Math.floor(p.x),Math.floor(p.y)],bombs:[p.bombsLive,p.bombsMax],placed:p.stats.bombs,ghostThrows:p.stats.ghostThrows||0,revivals:p.stats.revivals||0,disguise:!!p.disguise,ownBombs:bombs.filter(b=>b.owner===p&&!b.dead).map(b=>({ghost:!!b.ghost,airborne:!!b.airborne,disguised:!!b.disguised,tile:[Math.floor(b.x),Math.floor(b.y)],fuse:b.fuse}))})),
 time:()=>time,
 danger:(horizon=4.5)=>{let f=buildDangerForecast(clamp(+horizon||4.5,.2,12));return Object.fromEntries([...f.windows].map(([k,v])=>[k,v.map(w=>({start:w.start,end:w.end}))]))}
});
loadSettings();renderSlots();buildHelp();buildArena();requestAnimationFrame(loop);
