'use strict';
function draw(){ctx.clearRect(0,0,W,H);drawBackdrop();ctx.save();let sh=camera.shake;camera.x=sh?rand(sh,-sh):0;camera.y=sh?rand(sh,-sh):0;ctx.translate(camera.x,camera.y);drawArena();drawGhostRail();drawBombRangePreviews();drawItems();drawBombs();drawFlames();drawPlayers();drawEffects();ctx.restore();drawHUD();if(state==='playing'&&roundLocked&&roundTimer>0)drawRoundBanner();}
function drawBackdrop(){let g=ctx.createRadialGradient(500,300,40,500,300,720);g.addColorStop(0,'#142653');g.addColorStop(.45,'#071227');g.addColorStop(1,'#02040d');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);for(const p of particles)if(p.bg){ctx.globalAlpha=.22*(p.life/p.max);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;
 ctx.strokeStyle='rgba(69,224,255,.045)';ctx.lineWidth=1;for(let x=-H;x<W;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x+H,H);ctx.stroke()}}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawArena(){ctx.save();ctx.shadowColor='#38ddff';ctx.shadowBlur=25;rr(OX-7,OY-7,AW+14,AH+14,18);ctx.fillStyle='#0b1530';ctx.fill();ctx.shadowBlur=0;ctx.clip();
 let floor=ctx.createLinearGradient(OX,OY,OX,OY+AH);floor.addColorStop(0,'#0d1b3c');floor.addColorStop(1,'#080d22');ctx.fillStyle=floor;ctx.fillRect(OX,OY,AW,AH);
 for(let y=0;y<ROWS;y++)for(let x=0;x<COLS;x++){let px=OX+x*TILE,py=OY+y*TILE,g=grid[y][x];if(g===0){ctx.fillStyle=(x+y)%2?'rgba(37,123,168,.055)':'rgba(100,46,148,.04)';ctx.fillRect(px,py,TILE,TILE);ctx.strokeStyle='rgba(83,208,255,.055)';ctx.strokeRect(px+.5,py+.5,TILE-1,TILE-1)}else if(g===1)drawHardWall(px,py,x,y);else drawCrate(px,py,x,y)}
 ctx.restore();}
function drawGhostRail(){let x=OX+TILE/2,y=OY+TILE/2,w=GHOST_TRACK_W*TILE,h=GHOST_TRACK_H*TILE;ctx.save();ctx.setLineDash([5,9]);ctx.lineDashOffset=-time*18;ctx.strokeStyle='rgba(202,225,255,.18)';ctx.lineWidth=3;ctx.shadowColor='#a866ff';ctx.shadowBlur=10;ctx.strokeRect(x,y,w,h);ctx.setLineDash([]);ctx.strokeStyle='rgba(103,246,255,.14)';ctx.lineWidth=1;ctx.strokeRect(x-4,y-4,w+8,h+8);ctx.restore()}
function drawHardWall(px,py,x,y){let edge=x===0||y===0||x===COLS-1||y===ROWS-1;let g=ctx.createLinearGradient(px,py,px+TILE,py+TILE);g.addColorStop(0,edge?'#263960':'#223862');g.addColorStop(.5,'#101b3b');g.addColorStop(1,'#071126');ctx.fillStyle=g;ctx.fillRect(px,py,TILE,TILE);ctx.strokeStyle=edge?'rgba(74,238,255,.55)':'rgba(77,171,255,.34)';ctx.lineWidth=1.5;ctx.strokeRect(px+3,py+3,TILE-6,TILE-6);ctx.strokeStyle='rgba(255,255,255,.09)';ctx.beginPath();ctx.moveTo(px+7,py+10);ctx.lineTo(px+TILE-9,py+7);ctx.lineTo(px+TILE-7,py+TILE-10);ctx.stroke();if(!edge){ctx.fillStyle='rgba(52,228,255,.18)';ctx.fillRect(px+8,py+8,3,TILE-16);ctx.shadowColor='#42efff';ctx.shadowBlur=8;ctx.fillStyle='#4fefff';ctx.fillRect(px+9,py+TILE/2-4,2,8);ctx.shadowBlur=0}}
function drawCrate(px,py,x,y){ctx.save();let pulse=.5+.5*Math.sin(time*2+x*1.7+y);ctx.shadowColor='#c247ff';ctx.shadowBlur=5+pulse*5;let g=ctx.createLinearGradient(px,py,px+TILE,py+TILE);g.addColorStop(0,'#62206f');g.addColorStop(.5,'#271441');g.addColorStop(1,'#15102d');ctx.fillStyle=g;rr(px+4,py+4,TILE-8,TILE-8,7);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='rgba(255,84,225,.65)';ctx.lineWidth=2;ctx.stroke();ctx.strokeStyle='rgba(255,183,249,.22)';ctx.beginPath();ctx.moveTo(px+9,py+12);ctx.lineTo(px+TILE/2,py+6);ctx.lineTo(px+TILE-9,py+12);ctx.lineTo(px+TILE-11,py+TILE-11);ctx.lineTo(px+TILE/2,py+TILE-6);ctx.lineTo(px+10,py+TILE-11);ctx.closePath();ctx.stroke();ctx.fillStyle=`rgba(255,75,220,${.25+pulse*.25})`;ctx.fillRect(px+TILE/2-2,py+13,4,TILE-26);ctx.restore()}
function drawPowerIcon(g,id,x,y,size,color){
 g.save();g.translate(x,y);g.scale(size/32,size/32);g.lineWidth=2;g.lineCap='round';g.lineJoin='round';
 const ink='#06101d',light='#f4ffff',soft='#bce8f0';
 const finish=(fill=light,stroke=ink)=>{if(fill){g.fillStyle=fill;g.fill()}if(stroke){g.strokeStyle=stroke;g.stroke()}};
 const circle=(cx,cy,r,fill=light,stroke=ink)=>{g.beginPath();g.arc(cx,cy,r,0,Math.PI*2);finish(fill,stroke)};
 const line=(x1,y1,x2,y2,stroke=light,w=2)=>{g.beginPath();g.moveTo(x1,y1);g.lineTo(x2,y2);g.strokeStyle=stroke;g.lineWidth=w;g.stroke();g.lineWidth=2};
 const poly=(points,fill=light,stroke=ink)=>{g.beginPath();points.forEach((p,i)=>(i?g.lineTo(...p):g.moveTo(...p)));g.closePath();finish(fill,stroke)};
 switch(id){
  case'bomb':
   circle(1,3,9,light);g.beginPath();g.moveTo(5,-5);g.quadraticCurveTo(7,-12,12,-10);g.strokeStyle=ink;g.stroke();circle(12,-10,2.4,color,light);circle(-8,-7,4,color,ink);line(-10,-7,-6,-7,light,1.8);line(-8,-9,-8,-5,light,1.8);break;
  case'fire':
   g.beginPath();g.moveTo(0,14);g.bezierCurveTo(-11,11,-12,2,-5,-5);g.bezierCurveTo(-2,-8,-3,-12,1,-15);g.bezierCurveTo(2,-8,9,-7,10,1);g.bezierCurveTo(13,9,7,14,0,14);finish(light,ink);g.beginPath();g.moveTo(1,11);g.bezierCurveTo(-4,9,-4,4,0,-1);g.bezierCurveTo(1,4,6,5,5,9);g.bezierCurveTo(4,11,2,12,1,11);finish(color,null);break;
  case'speed':
   poly([[-12,5],[-5,4],[-1,-6],[7,-6],[5,0],[12,4],[9,9],[-5,9]],light,ink);line(-13,-5,-4,-5,soft,2.5);line(-15,0,-6,0,light,2.5);line(-14,11,8,11,color,2.5);poly([[2,-14],[10,-14],[5,-8],[10,-8],[-1,1],[2,-6],[-3,-6]],color,ink);break;
  case'kick':
   poly([[-11,-11],[-2,-11],[0,-1],[10,3],[12,9],[7,12],[-8,10],[-12,5]],light,ink);line(-8,7,8,9,color,3);line(12,-5,15,-8,light,2);line(13,0,16,0,light,2);line(12,5,15,8,light,2);break;
  case'glove':
   circle(-7,-5,5,light);circle(0,-8,5,light);circle(7,-5,5,light);g.beginPath();g.moveTo(-11,-3);g.lineTo(-9,7);g.quadraticCurveTo(-6,13,1,12);g.lineTo(8,8);g.quadraticCurveTo(12,3,8,-1);g.lineTo(3,3);g.lineTo(-2,0);g.closePath();finish(light,ink);poly([[-6,9],[6,8],[7,14],[-5,14]],color,ink);break;
  case'remote':
   g.beginPath();g.roundRect(-9,-10,18,23,4);finish(light,ink);line(3,-10,9,-15,light,2);circle(9,-15,1.8,color,ink);circle(-4,-4,2.5,color,ink);circle(4,3,2.5,ink,null);line(-5,7,5,7,ink,2);g.beginPath();g.arc(10,-7,5,-1.25,.2);g.strokeStyle=light;g.stroke();break;
  case'pierce':
   poly([[-14,-9],[-6,-9],[-6,-2],[-14,-2]],soft,ink);poly([[-14,3],[-6,3],[-6,10],[-14,10]],soft,ink);poly([[14,-9],[6,-9],[6,-2],[14,-2]],soft,ink);poly([[14,3],[6,3],[6,10],[14,10]],soft,ink);line(-13,0,9,0,light,3);poly([[8,-5],[15,0],[8,5]],color,ink);break;
  case'bombpass':
   circle(-7,6,6,soft,ink);g.beginPath();g.moveTo(-2,-11);g.quadraticCurveTo(7,-14,10,-5);g.lineTo(10,10);g.lineTo(6,7);g.lineTo(2,10);g.lineTo(-2,7);g.lineTo(-6,10);g.lineTo(-6,-5);g.quadraticCurveTo(-5,-9,-2,-11);finish(light,ink);circle(-1,-4,1.5,ink,null);circle(5,-4,1.5,ink,null);line(-13,13,13,-13,color,2.5);break;
  case'wallpass':
   for(const bx of[-12,7])for(const by of[-10,0,10]){g.beginPath();g.rect(bx,by-4,7,7);finish(soft,ink)}g.beginPath();g.moveTo(-4,-10);g.quadraticCurveTo(2,-14,6,-8);g.lineTo(6,9);g.lineTo(2,6);g.lineTo(-2,9);g.lineTo(-5,6);g.lineTo(-5,-7);g.quadraticCurveTo(-5,-9,-4,-10);finish(light,ink);circle(-1,-4,1.2,ink,null);circle(3,-4,1.2,ink,null);line(-14,15,14,-15,color,2.5);break;
  case'flamepass':
   poly([[0,-15],[12,-10],[10,3],[6,10],[0,14],[-6,10],[-10,3],[-12,-10]],light,ink);g.beginPath();g.moveTo(0,9);g.bezierCurveTo(-6,7,-6,1,-2,-3);g.quadraticCurveTo(0,-6,1,-10);g.quadraticCurveTo(8,-3,5,5);g.quadraticCurveTo(4,9,0,9);finish(color,ink);break;
  case'shield':
   poly([[0,-15],[12,-10],[10,4],[5,11],[0,15],[-5,11],[-10,4],[-12,-10]],light,ink);poly([[0,-9],[6,-6],[5,3],[0,9],[-5,3],[-6,-6]],color,null);line(-5,-13,-9,-9,light,2);line(-8,-13,-5,-10,light,2);break;
  case'heart':
   g.beginPath();g.moveTo(0,14);g.bezierCurveTo(-3,10,-13,4,-13,-4);g.bezierCurveTo(-13,-13,-3,-15,0,-8);g.bezierCurveTo(4,-15,13,-13,13,-4);g.bezierCurveTo(13,4,3,11,0,14);finish(light,ink);g.beginPath();g.moveTo(-8,1);g.lineTo(-4,1);g.lineTo(-1,-4);g.lineTo(3,6);g.lineTo(6,1);g.lineTo(10,1);g.strokeStyle=color;g.lineWidth=2.5;g.stroke();break;
  case'dash':
   poly([[1,-15],[12,-15],[5,-5],[12,-5],[-3,15],[0,2],[-8,2]],color,ink);line(-14,-8,-5,-8,light,2.5);line(-16,0,-7,0,light,2.5);line(-14,8,-5,8,light,2.5);break;
  case'mega':
   circle(0,2,8,light,ink);g.beginPath();g.moveTo(4,-5);g.quadraticCurveTo(7,-11,11,-9);g.strokeStyle=ink;g.stroke();for(let i=0;i<8;i++){let a=i*Math.PI/4;line(Math.cos(a)*11,Math.sin(a)*11+2,Math.cos(a)*15,Math.sin(a)*15+2,i%2?light:color,2)}circle(11,-9,2,color,light);break;
  case'cluster':
   for(const [cx,cy] of[[-9,-8],[9,-8],[-9,9],[9,9]]){line(0,0,cx,cy,soft,2);circle(cx,cy,4,color,ink)}circle(0,0,6,light,ink);circle(0,0,2,color,null);break;
  case'freeze':
   for(let i=0;i<3;i++){g.save();g.rotate(i*Math.PI/3);line(-14,0,14,0,light,2.4);line(9,0,5,-4,color,2);line(9,0,5,4,color,2);line(-9,0,-5,-4,color,2);line(-9,0,-5,4,color,2);g.restore()}circle(0,0,2.5,light,ink);break;
  case'magnet':
   g.beginPath();g.arc(0,-1,11,0,Math.PI);g.lineTo(-4,-1);g.arc(0,-1,4,Math.PI,0,true);g.lineTo(11,-1);g.closePath();finish(light,ink);poly([[-11,-2],[-4,-2],[-4,9],[-11,9]],color,ink);poly([[4,-2],[11,-2],[11,9],[4,9]],color,ink);line(-10,12,-4,12,light,2);line(4,12,10,12,light,2);break;
  case'reverse':
   line(-13,-6,8,-6,light,3);poly([[7,-11],[15,-6],[7,-1]],color,ink);line(13,7,-8,7,light,3);poly([[-7,2],[-15,7],[-7,12]],color,ink);break;
  case'slow':
   g.beginPath();g.moveTo(0,-14);g.bezierCurveTo(4,-7,11,-2,10,5);g.bezierCurveTo(9,12,-9,12,-10,5);g.bezierCurveTo(-11,-2,-4,-7,0,-14);finish(light,ink);g.beginPath();g.arc(0,3,5,-.3,Math.PI*1.65);g.strokeStyle=color;g.lineWidth=3;g.stroke();circle(3,2,1.6,color,null);line(-13,13,13,13,color,3);break;
  case'mystery':
   g.beginPath();g.roundRect(-12,-7,24,19,3);finish(light,ink);g.beginPath();g.rect(-14,-11,28,7);finish(color,ink);g.beginPath();g.rect(-2,-11,4,23);finish(soft,ink);g.beginPath();g.ellipse(-5,-14,6,3,-.45,0,Math.PI*2);finish(light,ink);g.beginPath();g.ellipse(5,-14,6,3,.45,0,Math.PI*2);finish(light,ink);line(12,-15,15,-15,color,2);line(13.5,-17,13.5,-13,color,2);break;
 }
 g.restore();
}
function drawItems(){for(const it of items){let p=POWERS[it.id],x=OX+it.x*TILE,y=OY+it.y*TILE+Math.sin(it.phase)*3,fade=Math.min(1,it.life/2);ctx.save();ctx.globalAlpha=fade;ctx.translate(x,y);ctx.rotate(Math.sin(it.phase*.7)*.08);ctx.shadowColor=p.color;ctx.shadowBlur=18;let g=ctx.createRadialGradient(-5,-7,2,0,0,20);g.addColorStop(0,'#fff');g.addColorStop(.18,p.color);g.addColorStop(1,'#131634');ctx.fillStyle=g;rr(-17,-17,34,34,10);ctx.fill();ctx.strokeStyle=p.color;ctx.lineWidth=2;ctx.stroke();ctx.shadowBlur=6;drawPowerIcon(ctx,it.id,0,1,25,p.color);ctx.restore()}}
function bombRangePreview(b){
 let x=Math.floor(b.x),y=Math.floor(b.y),shape=blastShape({x,y,range:b.range,mega:b.mega,pierce:b.pierce},grid),scatter=[];
 if(b.cluster&&shape.endpoints.length){
   let every=Math.max(1,Math.floor(shape.endpoints.length/6)),seen=new Set(shape.main.map(c=>key(c.x,c.y)));
   shape.endpoints.forEach((e,i)=>{if(i%every)return;for(const [dx,dy] of [[1,1],[-1,1],[1,-1],[-1,-1]]){let sx=e.x+dx,sy=e.y+dy,k=key(sx,sy);if(grid[sy]?.[sx]===0&&!seen.has(k)){seen.add(k);scatter.push({x:sx,y:sy})}}});
 }
 return{x,y,main:shape.main,scatter};
}
function drawBombRangePreviews(){
 for(const b of bombs){
   // Airborne bombs do not own a board cell yet, so their warning appears only after landing.
   if(b.dead||b.airborne)continue;
   let shape=bombRangePreview(b),ox=OX+(shape.x+.5)*TILE,oy=OY+(shape.y+.5)*TILE,color=b.mega?'#ffd84d':b.ghost?'#d9b9ff':b.owner.color;
   let ratio=clamp(b.fuse/(b.initialFuse||NORMAL_BOMB_FUSE),0,1),pulse=.5+.5*Math.sin(time*(7+4*(1-ratio))+b.born*3),alpha=.18+pulse*.08+(1-ratio)*.09;
   ctx.save();ctx.lineCap='round';ctx.lineJoin='round';ctx.shadowColor=color;ctx.shadowBlur=9+9*pulse;
   for(const [dx,dy] of AI_DIRS){
     let ray=shape.main.filter(c=>(dx?c.y===shape.y&&Math.sign(c.x-shape.x)===dx:c.x===shape.x&&Math.sign(c.y-shape.y)===dy));
     if(!ray.length)continue;let end=ray.reduce((a,c)=>Math.abs((dx?c.x:c.y)-(dx?shape.x:shape.y))>Math.abs((dx?a.x:a.y)-(dx?shape.x:shape.y))?c:a),ex=OX+(end.x+.5)*TILE,ey=OY+(end.y+.5)*TILE;
     ctx.globalAlpha=alpha*.42;ctx.strokeStyle=color;ctx.lineWidth=12;ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(ex,ey);ctx.stroke();
     ctx.globalAlpha=alpha*2.05;ctx.strokeStyle=color;ctx.lineWidth=2;ctx.setLineDash([8,8]);ctx.lineDashOffset=-time*22;ctx.beginPath();ctx.moveTo(ox,oy);ctx.lineTo(ex,ey);ctx.stroke();ctx.setLineDash([]);
   }
   for(const c of shape.main){
     if(c.x===shape.x&&c.y===shape.y)continue;let cx=OX+(c.x+.5)*TILE,cy=OY+(c.y+.5)*TILE,isCrate=grid[c.y]?.[c.x]===2;
     ctx.globalAlpha=alpha*(isCrate?1.65:1.05);ctx.fillStyle=color;ctx.beginPath();ctx.arc(cx,cy,isCrate?4.2:2.5,0,Math.PI*2);ctx.fill();
     if(isCrate){ctx.globalAlpha=alpha*1.5;ctx.strokeStyle=color;ctx.lineWidth=1.5;ctx.setLineDash([3,4]);ctx.strokeRect(cx-14,cy-14,28,28);ctx.setLineDash([])}
     let chained=bombs.some(other=>other!==b&&!other.dead&&!other.airborne&&Math.floor(other.x)===c.x&&Math.floor(other.y)===c.y);
     if(chained){ctx.globalAlpha=alpha*1.8;ctx.strokeStyle='#fff';ctx.lineWidth=1.4;ctx.beginPath();ctx.arc(cx,cy,10+pulse*2,0,Math.PI*2);ctx.stroke()}
   }
   if(shape.scatter.length){ctx.shadowColor='#9cff6c';ctx.strokeStyle='#9cff6c';ctx.lineWidth=1.5;ctx.setLineDash([2,5]);for(const c of shape.scatter){let cx=OX+(c.x+.5)*TILE,cy=OY+(c.y+.5)*TILE;ctx.globalAlpha=alpha*.95;ctx.beginPath();ctx.moveTo(cx,cy-8);ctx.lineTo(cx+8,cy);ctx.lineTo(cx,cy+8);ctx.lineTo(cx-8,cy);ctx.closePath();ctx.stroke()}ctx.setLineDash([])}
   ctx.restore();
 }
}
function drawCC0Bomb(r){if(!cc0BombSprite.complete||!cc0BombSprite.naturalWidth)return;ctx.save();ctx.globalCompositeOperation='screen';ctx.globalAlpha=.3;ctx.scale(-1,1);let s=r*2.5;ctx.drawImage(cc0BombSprite,-s/2,-s*.58,s,s);ctx.restore()}
function drawBombs(){for(const b of bombs){if(b.dead)continue;let flight=b.airborne,t=flight?clamp(flight.elapsed/flight.duration,0,1):0,lift=flight?Math.sin(t*Math.PI)*TILE*1.15:0,x=OX+b.x*TILE,y=OY+b.y*TILE-lift,bounce=flight?0:Math.sin(time*9+b.born)*2,ratio=clamp(b.fuse/(b.initialFuse||NORMAL_BOMB_FUSE),0,1);if(flight){ctx.save();ctx.globalCompositeOperation='lighter';for(let i=1;i<=5;i++){let q=i/6,tx=x+(OX+flight.fromX*TILE-x)*q,ty=y+(OY+flight.fromY*TILE-y)*q;ctx.globalAlpha=(1-q)*.35;ctx.fillStyle=i%2?'#fff':b.owner.color;ctx.shadowColor=b.owner.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(tx,ty,5-i*.6,0,Math.PI*2);ctx.fill()}ctx.restore()}ctx.save();ctx.translate(x,y+bounce);if(b.moving||flight)ctx.rotate(flight?t*13:time*10);ctx.shadowColor=b.mega?'#ffd84d':b.ghost?'#e8c9ff':b.owner.color;ctx.shadowBlur=b.mega?28:b.ghost?24:14;let r=b.mega?21:16,g=ctx.createRadialGradient(-6,-8,2,0,0,r);g.addColorStop(0,'#f8ffff');g.addColorStop(.18,b.ghost?'#d9c7ff':b.owner.color);g.addColorStop(.5,b.ghost?'#463b6b':'#20243b');g.addColorStop(1,'#03050d');ctx.fillStyle=g;ctx.beginPath();ctx.arc(0,2,r,0,Math.PI*2);ctx.fill();ctx.lineWidth=b.ghost?3:2;ctx.strokeStyle=b.ghost?'#f0d8ff':b.owner.color;ctx.stroke();drawCC0Bomb(r);ctx.shadowBlur=5;ctx.strokeStyle='#c8cfff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(5,-13);ctx.quadraticCurveTo(7,-24,16,-20);ctx.stroke();ctx.fillStyle=Math.sin(time*19)>0?'#fff':'#ff725c';ctx.shadowColor=b.ghost?'#c98cff':'#ff4b34';ctx.shadowBlur=12;ctx.beginPath();ctx.arc(17,-21,4+Math.sin(time*15),0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=b.ghost?'rgba(232,201,255,.72)':'rgba(255,255,255,.34)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,2,r+5,-Math.PI/2,-Math.PI/2+Math.PI*2*(1-ratio));ctx.stroke();if(b.ghost){ctx.setLineDash([3,4]);ctx.lineDashOffset=-time*16;ctx.strokeStyle=b.owner.color;ctx.beginPath();ctx.arc(0,2,r+9,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}if(b.cluster){ctx.fillStyle='#9cff6c';ctx.shadowColor='#9cff6c';ctx.shadowBlur=7;for(const [dx,dy] of[[-5,-3],[5,-3],[-5,6],[5,6]]){ctx.beginPath();ctx.arc(dx,dy,2.2,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0}ctx.restore()}}
function drawFlames(){let visible=new Map();for(const f of flames){let k=key(f.x,f.y),old=visible.get(k);if(!old||f.life>old.life)visible.set(k,f)}for(const f of visible.values()){let x=OX+(f.x+.5)*TILE,y=OY+(f.y+.5)*TILE,a=clamp(f.life/.18,0,1);ctx.save();ctx.translate(x,y);ctx.globalCompositeOperation='lighter';ctx.globalAlpha=a;ctx.rotate(Math.sin(time*9+f.seed)*.1);for(let i=0;i<3;i++){let r=(f.mega?31:25)-i*6+Math.sin(time*18+f.seed+i)*3,g=ctx.createRadialGradient(0,0,0,0,0,r);g.addColorStop(0,i===0?'#fff':'#fff29a');g.addColorStop(.28,i===2?'#ff62e6':'#ffd249');g.addColorStop(.7,i===2?'#7928ff':'#ff4b25');g.addColorStop(1,'rgba(255,30,80,0)');ctx.fillStyle=g;ctx.beginPath();for(let j=0;j<16;j++){let ang=j/16*Math.PI*2,spike=j%2?1:.72,rrr=r*spike;ctx.lineTo(Math.cos(ang)*rrr,Math.sin(ang)*rrr)}ctx.closePath();ctx.fill()}ctx.restore()}}
function drawLivingPlayer(p){let x=OX+p.x*TILE,y=OY+p.y*TILE,bob=Math.sin(time*9+p.id)*2;if(p.inv>0&&Math.floor(p.inv*10)%2===0)ctx.globalAlpha=.42;for(let i=0;i<p.trail.length;i++){let t=p.trail[i],a=(i/p.trail.length)*.12;ctx.globalAlpha=a;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(OX+t.x*TILE,OY+t.y*TILE,13,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;ctx.save();ctx.translate(x,y+bob);if(p.frozen>0){ctx.shadowColor='#73dfff';ctx.shadowBlur=22}else{ctx.shadowColor=p.color;ctx.shadowBlur=15}ctx.fillStyle=p.color;ctx.beginPath();ctx.ellipse(0,14,14,7,0,0,Math.PI*2);ctx.fill();let body=ctx.createLinearGradient(-15,-22,15,18);body.addColorStop(0,'#f8ffff');body.addColorStop(.25,p.color);body.addColorStop(1,'#13203b');ctx.fillStyle=body;rr(-15,-18,30,34,12);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.65)';ctx.lineWidth=2;ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle='#081325';rr(-12,-14,24,13,6);ctx.fill();let visor=ctx.createLinearGradient(-10,-12,10,-3);visor.addColorStop(0,'#fff');visor.addColorStop(.25,p.color);visor.addColorStop(1,'#41609a');ctx.fillStyle=visor;rr(-10,-12,20,9,4);ctx.fill();ctx.fillStyle=p.color;ctx.fillRect(-13,4,26,4);ctx.fillStyle='#07101e';ctx.beginPath();ctx.arc(-8,18,5,0,Math.PI*2);ctx.arc(8,18,5,0,Math.PI*2);ctx.fill();if(p.shield>0){ctx.strokeStyle=`rgba(102,234,255,${.55+.3*Math.sin(time*5)})`;ctx.lineWidth=2;ctx.shadowColor='#55eaff';ctx.shadowBlur=14;ctx.beginPath();ctx.arc(0,0,25+Math.sin(time*4)*2,0,Math.PI*2);ctx.stroke()}if(p.frozen>0){ctx.fillStyle='rgba(91,208,255,.33)';ctx.strokeStyle='#a4efff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(-22,20);ctx.lineTo(-17,-16);ctx.lineTo(0,-27);ctx.lineTo(19,-15);ctx.lineTo(22,20);ctx.closePath();ctx.fill();ctx.stroke()}ctx.restore();ctx.globalAlpha=1}
function drawGhostPlayer(p){
 let x=OX+p.x*TILE,y=OY+p.y*TILE,bob=Math.sin(time*5+p.id*1.7)*4,ready=!p.ghostBomb||p.ghostBomb.dead,cells=ready?ghostLandingCellsAt(p.ghostTrack,p.facing):[];
 if(cells.length){
   ctx.save();ctx.globalCompositeOperation='source-over';ctx.strokeStyle=p.color;ctx.fillStyle=p.color;ctx.lineWidth=1.4;
   cells.forEach((c,i)=>{let cx=OX+(c.x+.5)*TILE,cy=OY+(c.y+.5)*TILE,pulse=1+Math.sin(time*4+i*.8)*.12;ctx.globalAlpha=.18;ctx.beginPath();ctx.arc(cx,cy,7*pulse,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=.12;ctx.beginPath();ctx.moveTo(cx-10,cy);ctx.lineTo(cx+10,cy);ctx.moveTo(cx,cy-10);ctx.lineTo(cx,cy+10);ctx.stroke();ctx.globalAlpha=.2;ctx.beginPath();ctx.arc(cx,cy,2.2,0,Math.PI*2);ctx.fill()});
   ctx.restore();
 }
 ctx.save();ctx.translate(x,y+bob);ctx.globalCompositeOperation='screen';ctx.globalAlpha=.88;ctx.shadowColor=p.color;ctx.shadowBlur=24;
 let body=ctx.createLinearGradient(-14,-20,14,22);body.addColorStop(0,'#ffffff');body.addColorStop(.35,p.color);body.addColorStop(1,'rgba(113,74,190,.18)');ctx.fillStyle=body;ctx.beginPath();ctx.moveTo(-17,7);ctx.bezierCurveTo(-19,-12,-11,-22,0,-23);ctx.bezierCurveTo(13,-22,20,-11,17,8);ctx.lineTo(15,22);ctx.lineTo(8,16);ctx.lineTo(1,23);ctx.lineTo(-7,16);ctx.lineTo(-15,22);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(244,255,255,.82)';ctx.lineWidth=1.8;ctx.stroke();
 ctx.globalCompositeOperation='source-over';ctx.globalAlpha=1;ctx.shadowBlur=0;
 let fx=p.facing.x*3,fy=p.facing.y*3;ctx.fillStyle='#09112b';ctx.beginPath();ctx.ellipse(-6+fx,-5+fy,3.2,5,0,0,Math.PI*2);ctx.ellipse(6+fx,-5+fy,3.2,5,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(-5+fx,-7+fy,1.2,0,Math.PI*2);ctx.arc(7+fx,-7+fy,1.2,0,Math.PI*2);ctx.fill();ctx.strokeStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=10;ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(p.facing.x*19-p.facing.y*5,p.facing.y*19+p.facing.x*5);ctx.lineTo(p.facing.x*26,p.facing.y*26);ctx.lineTo(p.facing.x*19+p.facing.y*5,p.facing.y*19-p.facing.x*5);ctx.stroke();
 if(ready){let a=time*2.6+p.id*Math.PI/2,ox=Math.cos(a)*24,oy=Math.sin(a)*11;ctx.fillStyle='#11172f';ctx.strokeStyle=p.color;ctx.lineWidth=2;ctx.beginPath();ctx.arc(ox,oy,6,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.beginPath();ctx.moveTo(ox+2,oy-5);ctx.quadraticCurveTo(ox+4,oy-10,ox+8,oy-8);ctx.stroke()}
 ctx.restore();
}
function drawPlayers(){for(const p of players){if(p.alive)drawLivingPlayer(p);else if(p.ghost)drawGhostPlayer(p)}}
function drawEffects(){for(const p of particles)if(!p.bg){ctx.globalAlpha=clamp(p.life/p.max,0,1);ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=8;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.shadowBlur=0;ctx.globalAlpha=1;for(const s of shockwaves){ctx.globalAlpha=s.life/s.max;ctx.strokeStyle=s.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(OX+s.x*TILE,OY+s.y*TILE,s.r*TILE,0,Math.PI*2);ctx.stroke()}ctx.globalAlpha=1;for(const t of texts){ctx.globalAlpha=clamp(t.life/.3,0,1);ctx.textAlign='center';setCanvasFont(900,17);ctx.fillStyle=t.color;ctx.shadowColor=t.color;ctx.shadowBlur=10;ctx.fillText(t.text,t.x,t.y)}ctx.shadowBlur=0;ctx.globalAlpha=1}
function activePowerIndicators(p){let active=[],add=(condition,id)=>{if(condition)active.push(id)},own=bombs.filter(b=>b.owner===p&&!b.dead);add(p.bombsMax>1,'bomb');add(p.range>1,'fire');add(p.speed>3.16,'speed');add(p.kick,'kick');add(p.glove,'glove');add(p.remote,'remote');add(p.pierce,'pierce');add(p.bombpass,'bombpass');add(p.wallpass,'wallpass');add(p.flamepass,'flamepass');add(p.shield>0,'shield');add(p.hp>1,'heart');add(p.dash>0||p.dashing,'dash');add(p.mega>0||own.some(b=>b.mega),'mega');add(p.cluster>0||own.some(b=>b.cluster),'cluster');add(p.magnet,'magnet');add(p.frozen>0,'freeze');add(p.reverse>0,'reverse');add(p.slow>0,'slow');return active}
function drawActivePowerIndicators(p,x,y,w){let active=activePowerIndicators(p);if(!active.length)return;let split=active.length>12?Math.ceil(active.length/2):active.length,rows=active.length>12?[active.slice(0,split),active.slice(split)]:[active],rowGap=14;rows.forEach((row,r)=>{let step=Math.min(22,(w-24)/row.length),size=Math.max(13,Math.min(16,step-3)),cy=y+(r-(rows.length-1)/2)*rowGap,start=x+w/2-(row.length-1)*step/2;row.forEach((id,i)=>{let color=POWERS[id]?.color||EFFECT_COLORS[id],cx=start+i*step;ctx.save();ctx.shadowColor=color;ctx.shadowBlur=4;ctx.fillStyle='rgba(5,11,29,.94)';ctx.strokeStyle=color+'cc';ctx.lineWidth=1.2;ctx.beginPath();ctx.arc(cx,cy,Math.min(7.2,size*.48),0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=2;drawPowerIcon(ctx,id,cx,cy,size,color);ctx.restore()})})}
function drawHUD(){let x=884,y=55,w=364;ctx.save();let g=ctx.createLinearGradient(x,y,x+w,y+610);g.addColorStop(0,'rgba(13,25,61,.94)');g.addColorStop(1,'rgba(4,8,26,.94)');ctx.fillStyle=g;rr(x,y,w,610,20);ctx.fill();ctx.strokeStyle='rgba(77,227,255,.18)';ctx.stroke();ctx.fillStyle='#c9fbff';setCanvasFont(900,22);ctx.fillText('參賽者狀態',x+20,y+33);players.forEach((p,i)=>drawPlayerCard(p,x+15,y+50+i*132,w-30));ctx.fillStyle='#8da6ba';setCanvasFont(400,14);ctx.fillText('爆炸倒數約 1.9 秒　・　光軌顯示烈焰範圍',x+20,y+595);ctx.restore()}
function drawPlayerCard(p,x,y,w){
 ctx.save();ctx.globalAlpha=p.alive?1:p.ghost ? .78 : .36;ctx.fillStyle='rgba(255,255,255,.04)';rr(x,y,w,128,13);ctx.fill();ctx.strokeStyle=p.color+(p.ghost?'aa':'55');ctx.stroke();
 ctx.fillStyle=p.color;ctx.shadowColor=p.color;ctx.shadowBlur=p.ghost?16:10;ctx.beginPath();ctx.arc(x+21,y+23,8,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;setCanvasFont(900,18);ctx.fillText(p.name,x+38,y+29);ctx.fillStyle='#ffe573';setCanvasFont(900,15);ctx.fillText('♛'.repeat(p.wins)||'—',x+w-90,y+28);
 let ghostBusy=p.ghostBomb&&!p.ghostBomb.dead,ghostState=ghostBusy?(p.ghostBomb.airborne?'爆彈飛行中':'等待爆破'):'可投爆彈',ghostAiState=ghostBusy?'等待':p.aiMode==='幽靈追蹤'?'追蹤':p.aiMode==='幽靈伏擊'?'伏擊':'待命',status=p.ghost?(p.type==='ai'?`AI幽靈・${AI_LEVELS[p.aiLevel]?.label||'標準'}・${ghostAiState}`:`真人幽靈・${ghostState}`):(p.type==='ai'?`人工智慧・${AI_LEVELS[p.aiLevel]?.label||'標準'}・${p.aiMode}`:'真人操控');ctx.fillStyle=p.ghost?'#decfff':'#a9c0d2';setCanvasFont(700,14);ctx.fillText(status,x+15,y+54);
 let hearts='♥'.repeat(Math.max(0,p.hp)),shields='◆'.repeat(p.shield);setCanvasFont(900,15);ctx.fillStyle=p.ghost?'#e7d5ff':'#ff6d91';ctx.fillText(p.ghost?'幽靈':hearts||'出局',x+w-105,y+54);ctx.fillStyle='#65eaff';ctx.fillText(shields,x+w-50,y+54);
 let arrow=p.facing.y<0?'↑':p.facing.y>0?'↓':p.facing.x<0?'←':'→',stats=p.ghost?[['魂','外圈'],['彈',ghostBusy?'等待':'就緒'],['向',arrow],['復',p.stats.revivals||0]]:[['彈',`${p.bombsMax-p.bombsLive}/${p.bombsMax}`],['焰',p.range],['速',p.speed.toFixed(1)],['技',p.remote?'遙控':p.glove?'拳套':p.dash?'衝刺':'—']];stats.forEach((s,i)=>{let xx=x+15+i*78;ctx.fillStyle='rgba(255,255,255,.065)';rr(xx,y+62,70,32,7);ctx.fill();ctx.fillStyle=i===0?'#ffd44e':i===1?'#ff755b':i===2?'#64ffba':'#bd94ff';setCanvasFont(900,12);ctx.fillText(s[0],xx+7,y+84);ctx.fillStyle='#f2faff';setCanvasFont(800,14);ctx.fillText(s[1],xx+27,y+84)});drawActivePowerIndicators(p,x,y+112,w);ctx.restore()
}
function drawRoundBanner(){ctx.save();ctx.textAlign='center';ctx.fillStyle='rgba(2,5,16,.58)';ctx.fillRect(0,H/2-70,W,140);setCanvasFont(1000,52);ctx.fillStyle=winner?winner.color:'#fff';ctx.shadowColor=ctx.fillStyle;ctx.shadowBlur=25;ctx.fillText(winner?`${winner.name} 存活！`:'全員爆破！',W/2,H/2+18);ctx.restore()}
