'use strict';
function cancelGhostBomb(b){b.dead=true;if(b.source)b.source.reviveUsed=true;if(b.owner.ghostBomb===b)b.owner.ghostBomb=null;burst(b.x,b.y,b.owner.color,10,1.4)}
function landGhostBomb(b){let a=b.airborne,choices=a.cells.filter(c=>grid[c.y]?.[c.x]===0&&!bombReservationAt(c.x,c.y,b));if(!choices.length)for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(grid[y][x]===0&&!bombReservationAt(x,y,b))choices.push({x,y});let cell=choices.sort((c,d)=>(Math.abs(c.x-a.toX)+Math.abs(c.y-a.toY))-(Math.abs(d.x-a.toX)+Math.abs(d.y-a.toY)))[0];if(!cell){cancelGhostBomb(b);return false}b.x=cell.x+.5;b.y=cell.y+.5;b.airborne=null;b.born=time;b.passers=new Set(players.filter(p=>p.alive&&playerOverlapsCell(p,cell.x,cell.y)).map(p=>p.id));burst(b.x,b.y,b.owner.color,13,1.8);sfx.kick();return true}
function updateBombs(dt){
 for(const b of bombs){if(b.dead)continue;if(b.airborne){let a=b.airborne;a.elapsed+=dt;let t=clamp(a.elapsed/a.duration,0,1),ease=t*t*(3-2*t);b.x=a.fromX+(a.toX+.5-a.fromX)*ease;b.y=a.fromY+(a.toY+.5-a.fromY)*ease;if(t>=1)landGhostBomb(b);continue}b.fuse-=dt;if(b.moving){let speed=6,nx=b.x+b.moving.x*speed*dt,ny=b.y+b.moving.y*speed*dt,tx=Math.floor(nx),ty=Math.floor(ny);if(canBombEnter(tx,ty,b)){b.x=nx;b.y=ny}else{b.x=Math.floor(b.x)+.5;b.y=Math.floor(b.y)+.5;b.moving=null;sfx.kick()}}
   if(b.fuse<=0)explodeBomb(b);
 }
 bombs=bombs.filter(b=>!b.dead);
}
function explodeBomb(b){
 if(!b||b.dead||b.airborne)return;b.dead=true;if(b.ghost){if(b.owner.ghostBomb===b)b.owner.ghostBomb=null}else b.owner.bombsLive=Math.max(0,b.owner.bombsLive-1);let source=b.source||(b.source=makeBombSource(b.owner,!!b.ghost)),bx=Math.floor(b.x),by=Math.floor(b.y),range=b.range+(b.mega?2:0);addFlame(bx,by,source,b.mega);let endpoints=[];
 for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){let pierced=false;for(let i=1;i<=range;i++){let x=bx+dx*i,y=by+dy*i,g=grid[y]?.[x];if(g===1)break;addFlame(x,y,source,b.mega);let other=bombAt(x,y);if(other&&!other.dead){other.fuse=Math.min(other.fuse,.035)}if(g===2){grid[y][x]=0;b.owner.stats.boxes++;dropItem(x,y);if(!b.pierce||pierced)break;pierced=true}endpoints.push({x,y})}}
 if(b.cluster){for(const e of endpoints.filter((_,i)=>i%Math.max(1,Math.floor(endpoints.length/6))===0))for(const [dx,dy] of [[1,1],[-1,1],[1,-1],[-1,-1]]){let x=e.x+dx,y=e.y+dy;if(grid[y]?.[x]===0){addFlame(x,y,source,false,.58);let other=bombAt(x,y);if(other&&!other.dead)other.fuse=Math.min(other.fuse,.035)}}}
 camera.shake=Math.max(camera.shake,b.mega?19:9);shockwaves.push({x:bx+.5,y:by+.5,r:0,life:b.mega?.8:.55,max:b.mega?.8:.55,color:b.owner.color});burst(bx+.5,by+.5,b.mega?'#fff3aa':'#ff6a3d',b.mega?55:26,b.mega?5:3);sfx.boom(b.mega);
}
function addFlame(x,y,source,mega=false,life=.75){let existing=flames.find(f=>f.x===x&&f.y===y&&f.source===source);if(existing){existing.life=Math.max(existing.life,life);return}flames.push({x,y,owner:source.owner,source,life,max:life,mega,seed:rand(99)});}
function dropItem(x,y){if(Math.random()>loot)return;let pool=[];for(const [id,p] of Object.entries(POWERS))for(let n=0;n<p.weight;n++)pool.push(id);let id=pool[Math.floor(rand(pool.length))];items.push({x:x+.5,y:y+.5,id,life:18,dead:false,phase:rand(Math.PI*2)});}
function becomeGhost(p,deathX,deathY){p.alive=false;p.ghost=true;p.ghostGeneration=(p.ghostGeneration||0)+1;p.stun=0;p.frozen=0;p.reverse=0;p.slow=0;p.dashing=0;p.trail=[];bombs.forEach(b=>b.passers.delete(p.id));p.ghostTrack=ghostTrackFromPosition(deathX,deathY);let pos=ghostPoint(p.ghostTrack);p.x=pos.x;p.y=pos.y;p.facing={...pos.inward};p.ghostThink=0;p.ghostAim=null;p.aiGoal=null;p.aiWaypoint=null;p.aiRoute=[];p.aiRouteIndex=0;p.aiRouteLock=false;p.aiMode='幽靈追蹤'}
function retireGhostBombs(p){for(const b of bombs)if(!b.dead&&b.ghost&&b.owner===p)cancelGhostBomb(b);for(const f of flames)if(f.source?.ghost&&f.source.owner===p)f.source.reviveUsed=true;p.ghostBomb=null}
function reviveGhost(p,x,y){retireGhostBombs(p);p.alive=true;p.ghost=false;p.x=x;p.y=y;p.hp=1;p.inv=2.2;p.stun=0;p.frozen=0;p.reverse=0;p.slow=0;p.dashing=0;p.trail=[];p.ghostAim=null;p.aiThink=0;p.aiBombCd=1;p.aiGoal=null;p.aiWaypoint=null;p.aiRoute=[];p.aiRouteIndex=0;p.aiRouteLock=false;p.aiMode='復活';p.bombsLive=bombs.filter(b=>!b.dead&&!b.ghost&&b.owner===p).length;bombs.filter(b=>!b.dead&&!b.airborne&&playerOverlapsCell(p,Math.floor(b.x),Math.floor(b.y))).forEach(b=>b.passers.add(p.id));p.stats.revivals=(p.stats.revivals||0)+1;burst(x,y,p.color,48,4);textPop(x,y-.45,'幽靈復活！',p.color);sfx.pickup()}
function resolveGhostRevives(kills){if(roundLocked||players.filter(p=>p.alive).length<=1)return;for(const kill of kills){let source=kill.source,owner=source?.owner;if(!source?.ghost||source.reviveUsed||!owner||owner===kill.victim||owner.alive||!owner.ghost||source.ghostGeneration!==owner.ghostGeneration)continue;source.reviveUsed=true;reviveGhost(owner,kill.x,kill.y)}}
function updateFlames(dt){let kills=[];for(const f of flames){f.life-=dt;if(f.life<=0)continue;let other=bombAt(f.x,f.y);if(other&&!other.dead)other.fuse=Math.min(other.fuse,.035);for(const p of players)if(p.alive&&Math.floor(p.x)===f.x&&Math.floor(p.y)===f.y){let kill=hurtPlayer(p,f.source);if(kill)kills.push(kill)}}if(players.filter(p=>p.alive).length<=1)lockRound();else resolveGhostRevives(kills);flames=flames.filter(f=>f.life>0)}
function hurtPlayer(p,source){if(p.inv>0||p.flamepass)return null;let attacker=source?.owner||null,selfHit=attacker===p;if(p.type==='ai'&&selfHit)p.aiStats.selfHits=(p.aiStats.selfHits||0)+1;if(p.shield>0){p.shield--;p.inv=1.2;sfx.shield();textPop(p.x,p.y-.5,'護盾吸收！','#79eaff');burst(p.x,p.y,'#66eaff',24,2);return null}p.hp--;p.inv=1.65;sfx.hit();camera.shake=Math.max(camera.shake,12);if(p.hp<=0){let deathX=p.x,deathY=p.y;if(p.type==='ai'&&selfHit)p.aiStats.selfDeaths=(p.aiStats.selfDeaths||0)+1;p.lastHit={by:attacker?.id??null,self:selfHit,ghost:!!source?.ghost,at:time,tile:[Math.floor(deathX),Math.floor(deathY)]};burst(deathX,deathY,p.color,42,3.5);textPop(deathX,deathY-.4,'化為幽靈！',p.color);becomeGhost(p,deathX,deathY);return{victim:p,source,x:deathX,y:deathY}}textPop(p.x,p.y-.4,'生命 -1','#ff7894');return null}
function collectItems(p,dt){for(const it of items){if(it.dead)continue;if(p.magnet){let d=dist(p,it);if(d<MAGNET_ATTRACTION_RADIUS){it.x+=(p.x-it.x)*dt*3.5;it.y+=(p.y-it.y)*dt*3.5}}if(dist(p,it)<.52){it.dead=true;applyPower(p,it.id);sfx.pickup();burst(it.x,it.y,POWERS[it.id].color,18,2)}}items=items.filter(i=>!i.dead)}
function applyPower(p,id){let po=POWERS[id],msg=po.name;switch(id){case'bomb':p.bombsMax=Math.min(9,p.bombsMax+1);break;case'fire':p.range=Math.min(10,p.range+1);break;case'speed':p.speed=Math.min(5.2,p.speed+.34);break;case'kick':p.kick=true;break;case'glove':p.glove=true;break;case'remote':p.remote=true;break;case'disguise':p.disguise=true;break;case'pierce':p.pierce=true;break;case'bombpass':p.bombpass=true;break;case'wallpass':p.wallpass=true;break;case'flamepass':p.flamepass=true;break;case'shield':p.shield=Math.min(3,p.shield+1);break;case'heart':p.hp=Math.min(3,p.hp+1);break;case'dash':p.dash=Math.min(5,p.dash+2);break;case'mega':p.mega=Math.min(3,p.mega+1);break;case'cluster':p.cluster=Math.min(3,p.cluster+1);break;case'freeze':players.forEach(q=>{if(q!==p&&q.alive)q.frozen=Math.max(q.frozen,2.2)});msg='零度脈衝！';break;case'magnet':p.magnet=true;break;case'mystery':mystery(p);return}textPop(p.x,p.y-.55,msg,po.color)}
function mystery(p){let r=Math.random();if(r<.20){p.reverse=6;textPop(p.x,p.y-.5,'方向反轉！','#ff72cf')}else if(r<.38){p.slow=6;textPop(p.x,p.y-.5,'黏液減速！','#92d858')}else if(r<.55){teleport(p);textPop(p.x,p.y-.5,'量子傳送！','#d78bff')}else if(r<.72){p.shield+=2;textPop(p.x,p.y-.5,'雙重護盾！','#6ceaff')}else if(r<.88){p.mega+=2;p.cluster+=1;textPop(p.x,p.y-.5,'毀滅套餐！','#ffd359')}else{p.bombsMax=Math.min(9,p.bombsMax+2);p.range=Math.min(10,p.range+2);p.speed=Math.min(5.2,p.speed+.5);textPop(p.x,p.y-.5,'全面超載！','#fff')}}
function teleport(p){let cells=[];for(let y=1;y<ROWS-1;y++)for(let x=1;x<COLS-1;x++)if(grid[y][x]===0&&!bombAt(x,y))cells.push([x,y]);if(cells.length){let c=cells[Math.floor(rand(cells.length))];p.x=c[0]+.5;p.y=c[1]+.5;p.inv=1}}

function updateEffects(dt){for(const it of items){it.life-=dt;it.phase+=dt*3;if(it.life<=0)it.dead=true}items=items.filter(i=>!i.dead);for(const p of particles){p.life-=dt;p.x+=p.vx*dt*(p.bg?30:1);p.y+=p.vy*dt*(p.bg?30:1);if(!p.bg)p.vy+=dt*1.8}particles=particles.filter(p=>p.life>0);for(const t of texts){t.life-=dt;t.y-=dt*.6}texts=texts.filter(t=>t.life>0);for(const s of shockwaves){s.life-=dt;s.r+=(s.max>0?9:5)*dt}shockwaves=shockwaves.filter(s=>s.life>0);camera.shake=Math.max(0,camera.shake-dt*28)}
function burst(x,y,color,n=12,speed=2){for(let i=0;i<n;i++){let a=rand(Math.PI*2),v=rand(speed,.25);particles.push({x:OX+x*TILE,y:OY+y*TILE,vx:Math.cos(a)*v*TILE,vy:Math.sin(a)*v*TILE,life:rand(.7,.25),max:.7,size:rand(5,1.5),color,bg:false})}}
function textPop(x,y,text,color){texts.push({x:OX+x*TILE,y:OY+y*TILE,text,color,life:1.2,max:1.2})}
function lockRound(){if(roundLocked)return;let alive=players.filter(p=>p.alive);winner=alive.length===1?alive[0]:null;if(winner)winner.wins++;roundLocked=true;roundTimer=2.1}
function checkRound(dt){if(state!=='playing')return;if(roundLocked){roundTimer-=dt;if(roundTimer<=0)endRound();return}if(players.filter(p=>p.alive).length<=1)lockRound()}
function endRound(){state='roundover';let champion=winner&&winner.wins>=targetWins;if(champion){sfx.win();$('#announceTitle').textContent='競技場霸主！';$('#announceTitle').style.color=winner.color;$('#announceText').textContent=`${winner.name} 集滿 ${winner.wins} 頂皇冠，成為本次混沌之王！`;$('#nextBtn').textContent='再戰一場';$('#nextBtn').onclick=()=>{players.forEach(p=>p.wins=0);round=1;$('#announcement').classList.add('hidden');newRound()}}else{$('#announceTitle').textContent=winner?`${winner.name} 勝出！`:'同歸於盡！';$('#announceTitle').style.color=winner?winner.color:'#e8efff';$('#announceText').textContent=winner?`漂亮存活，皇冠數來到 ${winner.wins}／${targetWins}。`:'烈焰吞沒了所有參賽者，本回合無人得冠。';$('#nextBtn').textContent='下一回合';$('#nextBtn').onclick=()=>{round++;$('#announcement').classList.add('hidden');newRound()}}$('#announcement').classList.remove('hidden')}
